version: 2
       
sources:
  - name: qwt_raw
    database: "{{ env_var('DBT_SOURCEDB', 'QWTANALYTICS_DEV')}}"
    schema:   "{{ env_var('DBT_SOURCESCHEMA', 'RAW_DEV')}}"
    tables: 
      - name : customers
      - name : orders
      - name : order_details
      - name : shipments
      - name : products
      - name: employees
      
      - name: suppliers_xml
    